# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moda',
                'doc_host': 'https://ACCLAB.github.io',
                'git_url': 'https://github.com/ACCLAB/moda',
                'lib_path': 'moda'},
  'syms': {'moda.core': {'moda.core.foo': ('core.html#foo', 'moda/core.py')}, 'moda.moda': {}}}